### ISSUE TITLE
Console spam from ET Laser lense

### ISSUE THREAD

**Issue by OrdinatorStouff** [AllTheMods/ATM-2#30]
Doesn't crash server or make crash-report just spamming in STERR

`[04:53:53] [Server thread/ERROR] [FML]: A TileEntity environmentaltech:laser_core.tile(com.valkyrieofnight.environmentaltech.block.multiblock.voidoreminer.BlockLaserCore$LL_SLAVE) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.InstantiationException: com.valkyrieofnight.environmentaltech.block.multiblock.voidoreminer.BlockLaserCore$LL_SLAVE
	at java.lang.Class.newInstance(Class.java:427) ~[?:1.8.0_111]
	at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:105) [asc.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:490) [avd.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:119) [lv.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:90) [lv.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:136) [lv.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:303) [ajs.class:?]
	at net.minecraft.world.World.func_175726_f(World.java:298) [ajs.class:?]
	at net.minecraft.world.World.func_175625_s(World.java:2359) [ajs.class:?]
	at me.modmuss50.fr.mutlipart.PipeMultipart.func_73660_a(PipeMultipart.kt:271) [PipeMultipart.class:?]
	at reborncore.mcmultipart.block.TileMultipartContainer$Ticking.func_73660_a(TileMultipartContainer.java:312) [TileMultipartContainer$Ticking.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1802) [ajs.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621) [lw.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NoSuchMethodException: com.valkyrieofnight.environmentaltech.block.multiblock.voidoreminer.BlockLaserCore$LL_SLAVE.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_111]
	at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_111]
	... 19 more
[04:53:53] [Server thread/WARN]: Skipping BlockEntity with id environmentaltech:laser_core.tile`

**Comment by Boomflex** [comment]
Valkyrie working on an update.

Will close this when update released.

**Comment by Boomflex** [comment]
Old issue.

Fixed in newer builds.
